### ISSUE TITLE
error

### ISSUE THREAD

**Issue by m0iises19** [ESX-PUBLIC/esx_adrp_vehicle#4]
show this console error

![Sin título](https://user-images.githubusercontent.com/10025085/76023119-d11eab00-5f28-11ea-96f2-9f520985d85c.png)

**Comment by m0iises19** [comment]
any solution?

**Comment by xnubil** [comment]
do you have a limit column in your items table?

**Comment by m0iises19** [comment]
no, it is defined by “weight”

**Comment by xnubil** [comment]
Looks like it is written for old limit system, this script loaded fine on my server with limit system

> if playerItem.**limit** ~= -1 and (playerItem.count + count) > playerItem.**limit** then

**Comment by ManuDay** [comment]
The trunk may not be linked to the database. This is why this error occurs. I am not a master developer, but if I have trunk scripts, it is linked to the database

**Comment by ManuDay** [comment]
instead of if playerItem.limit ~= -1 and (playerItem.count + count) > playerItem.limit then
cb(false, _U('error_remove_playerlimit' do you if playerItem.weight ~= -1 and (playerItem.count + count) > playerItem.weight then cb(false, _U('error_remove_playerweight'
